---
- name: Configure Server & Deploy Container Applications
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure python3-apt is installed/reinstalled
      apt:
        name: python3-apt
        state: present
        update_cache: yes

    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
          - python3-pip
          - rsync
        state: present

    - name: Add Docker’s official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker repository using deb822_repository
      deb822_repository:
        name: docker
        types: [deb]
        uris: ["https://download.docker.com/linux/ubuntu"]
        suites: ["{{ ansible_distribution_release }}"]
        components: ["stable"]
        architectures: ["amd64"]
        signed_by: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Install Docker Engine & Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Synchronize project repository files to server
      synchronize:
        src: "../"
        dest: "/home/ubuntu/app"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=terraform"

    - name: Clone project repository
      ansible.builtin.git:
        repo: 'https://github.com/emmalux2/devops-capstone-project.git'
        dest: /home/ubuntu/devops-capstone-project
        version: main

    - name: Debug - list project directory contents
      ansible.builtin.command:
        cmd: ls -la
        chdir: /home/ubuntu/devops-capstone-project

    - name: Deploy applications using Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d --build
        chdir: /home/ubuntu/devops-capstone-project
